name: wack_ui
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.1.3+1
  flutter_mobx: ^2.0.6+5
  provider: ^6.0.5

  config_repo:
    path: ../../repos/config_repo
  git_host_repo:
    path: ../../repos/git_host_repo
  ticket_host_repo:
    path: ../../repos/ticket_host_repo

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1

flutter:
  uses-material-design: true