name: wack_cli
description: A Very Good Project created by Very Good CLI.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.3.1
  atlassian_apis: ^0.11.0
  dotenv: ^4.1.0
  env_variables: ^1.0.1
  git: ^2.2.0
  mason_logger: ^0.2.0
  path: ^1.8.3
  pub_updater: ^0.2.4

  config_repo:
    path: ../../repos/config_repo
  git_host_repo:
    path: ../../repos/git_host_repo
  ticket_host_repo:
    path: ../../repos/ticket_host_repo


dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0

executables:
  wack_cli:
